// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VirtoCommerce.CatalogModule.Data.Repositories;

#nullable disable

namespace VirtoCommerce.CatalogModule.Data.PostgreSql.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260302000000_Catalog_AddCategoryAssets")]
    partial class Catalog_AddCategoryAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
