// <auto-generated />
namespace VirtoCommerce.CatalogModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PropertyDisplayNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropertyDisplayNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201706261011171_PropertyDisplayNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
