# v3.200.10
name: Release hotfix

on:
  workflow_dispatch:

jobs:
  build:
    uses: VirtoCommerce/.github/.github/workflows/build.yml@v3.200.10
    with:
      uploadPackage: 'true'
      uploadDocker: 'false'
      forceVersionSuffix: 'false'
      eventName: ${{ github.event_name }}
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}

  test:
    uses: VirtoCommerce/.github/.github/workflows/test-and-sonar.yml@v3.200.10
    secrets:
      sonarToken: ${{ secrets.SONAR_TOKEN }}

  get-metadata:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: 'platform'
      DOCKER_CACHE_KEY: ''
      DOCKER_TAR: 'image.tar'
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Changelog
      id: changelog
      uses: VirtoCommerce/vc-github-actions/changelog-generator@master

  publish-github-release:
    needs:
      [build, test, get-metadata]
    uses: VirtoCommerce/.github/.github/workflows/publish-github.yml@v3.200.10
    with:
      fullKey: ${{ needs.build.outputs.packageFullKey }}
      changeLog: '${{ needs.get-metadata.outputs.changeLog }}'

    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }}
      nugetKey: ${{ secrets.NUGET_KEY }}
