name: Sync
'on':
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  github-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: VirtoCommerce/vc-github-actions/sync-module-cicd@feature/vp-3187-initial-ci
      with:
        github_token: ${{ secrets.REPO_GITHUB_WORKFLOW_TOKEN }}
